# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-12 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='m_inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kategori', models.CharField(max_length=60)),
                ('lokasi', models.CharField(max_length=60)),
                ('nama', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='m_pengajuan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nis', models.IntegerField()),
                ('nama', models.CharField(max_length=60)),
                ('nohp', models.CharField(max_length=60)),
                ('item', models.IntegerField()),
                ('jabatan', models.CharField(max_length=60)),
                ('kegunaan', models.CharField(max_length=60)),
                ('flag', models.IntegerField()),
                ('tanggal', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='m_user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
                ('jabatan', models.CharField(max_length=60)),
            ],
        ),
    ]
