# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-13 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peminjam', '0002_auto_20180412_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_pengajuan',
            name='waktu',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
