# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-13 13:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peminjam', '0003_m_pengajuan_waktu'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_pengajuan',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
